//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseLimit
    {
        public int ExpenseLimitId { get; set; }
        public int TotalExpense { get; set; }
        public int ExpenseLimit1 { get; set; }
    }
}
